# -*- coding: utf-8 -*-
"""Performance Modele.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDLDveFG2LBmgVtfZDxvyTmKUZ4ODoBM
"""

!pip install -q git+https://github.com/moritztng/prism.git
from IPython.display import Image

Image('content.jpg')

Image('style.jpg')

!style-transfer content.jpg style.jpg --iter 100 --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --iter 300 --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --iter 500 --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --iter 700 --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --iter 900 --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.25 --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.25 --use_adam --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.25 --use_adam --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.25 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.25 --content_weight 8 --style_weight 100 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.25 --content_weight 8 --style_weight 300 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.25 --content_weight 8 --style_weight 500 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.25 --content_weight 8 --style_weight 700 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.25 --content_weight 8 --style_weight 900 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.5 --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.5 --use_adam --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.5 --use_adam --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.5 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.5 --content_weight 8 --style_weight 300 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.5 --content_weight 8 --style_weight 500 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.5 --content_weight 8 --style_weight 700 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.5 --content_weight 8 --style_weight 900 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.75 --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.75 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.75 --use_adam --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.75 --avg_pool --use_adam --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.75 --content_weight 8 --style_weight 300 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.75 --content_weight 8 --style_weight 500 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.75 --content_weight 8 --style_weight 700 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --lr 0.75 --content_weight 8 --style_weight 900 --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --avg_pool --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --use_adam --use_amp --area 1100
Image('artwork.png')

!style-transfer content.jpg style.jpg --artwork artwork.png --iter 500 --use_amp --area 500
Image('artwork.png')